### ISSUE TITLE
Can't install Uproot 4

### ISSUE THREAD

**Issue by Superharz** [conda-forge/uproot-feedstock#74] opened 2020-12-20 02:24 UTC
Has ```Uproot 4.0.0``` been uploaded to Anaconda yet?
It's listet on the Anaconda website (https://anaconda.org/conda-forge/uproot/files) but the file is only ```6.6 kB``` large and conda fails to install it for me under Windows 10.

**Comment by henryiii** [comment] 2020-12-20 03:32
> fails to install it for me

What does the failure look like? There might have been some issues with the initial upload; there's a build=1 upload from a few hours ago that should be fine. It installs correctly for me on macOS.

> file is only 6.6 kB large

It's actually in uproot-base, the uproot package is just the not-strictly-required but recommended dependencies on top of uproot-base, which does have just the strictly required dependencies.

**Comment by chrisburr** [comment] 2020-12-20 11:41
The issue is that I forgot that XRootD hasn't been built for Windows. You could install `uproot-base` as a workaround while I debate building on Windows or removing the dependency from the main `uproot` conda package.

**Comment by Superharz** [comment] 2020-12-20 13:48
Thank you for your replies.

> install uproot-base as a workaround

This works.

> What does the failure look like?
```
(awkward_test) C:\Windows\system32>conda install uproot==4.0.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

```
This is the full output.

**Comment by henryiii** [comment] 2020-12-20 14:38
You could make it a non-Windows only dependency. Though if it could be built on windows, that would be great - having as few differences as possible is a good goal.

**Comment by chrisburr** [comment] 2020-12-21 06:45
It looks like XRootD is completely broken on Windows and has been for a very long time. I could be wrong but without access to a Windows machine it's too tedious for me to keep trying using the conda-forge's CI to test: https://github.com/conda-forge/xrootd-feedstock/pull/37

This should be fixed once https://github.com/conda-forge/uproot-feedstock/pull/75/ is merged (modulo an hour or so for it to build and the CDN to update). Thanks for reporting, I would never have noticed I broke this! 😄 

> UnsatisfiableError: The following specifications were found to be incompatible with each other:

In case it's useful for the future, mamba tends to give much better errors in these situations: https://github.com/mamba-org/mamba/

**Closed** 2020-12-21 11:00 UTC

**Comment by Superharz** [comment] 2020-12-21 21:16
Thank you!
It works for me.
